@startuml leave_comment
actor Reader
boundary "Actions" as actions
control "Sessions" as sessions
activate actions
Reader -> actions: leave_comment(url, comment)
actions ->> Reader: return to user control
deactivate actions
@enduml
