@startuml delete_comment
actor Artist
boundary "Actions" as actions
control "Sessions" as sessions
activate actions
Artist -> actions: delete_comment(url, comment_id, db)
actions --> Artist: return to artist control
deactivate actions
@enduml
