@startuml
left to right direction

actor User as U
rectangle Site {
  U -- (Navigate through comic pages with back and forward buttons)
}
left to right direction

actor User as U
rectangle Site {
  U -- (Navigate through comic pages with back and forward buttons)
}

@enduml
