@startuml packages
set namespaceSeparator none
package "authentication" as authentication #aliceblue {
}
package "authentication.authTools" as authentication.authTools #aliceblue {
}
left to right direction

actor User as U
rectangle Site {
  U -- (Navigate through comic pages with back and forward buttons)
}

@enduml
