@startuml classes
set namespaceSeparator none
class "Sessions" as core.session.Sessions #aliceblue {
  sessions : dict
  add_new_session(username: str, db: Database) -> None
  get_all_sessions() -> dict
  get_session(username: str) -> UserSession
  remove_session(username: str) -> None
}
class "AnonymousSession" as core.session.AnonymousSession #aliceblue {
  type : int
  date : NoneType, datetime
  db : Database
  navigate_page(url: str) -> None
  get_share_link() -> str
  login(username: str, password: str) -> None
}
class "ReaderSession" as core.session.ReaderSession #aliceblue {
  type : int
  date : NoneType, datetime
  db : Database
  username : str
  navigate_page(url: str) -> None
  get_share_link() -> str
  bookmark_page(url: str, db: Database) -> None
  leave_comment(url: str, comment: str) -> None
  edit_comment(url: str, comment_id: int, comment: str) -> None
  logout() -> None
}
class "ArtistSession" as core.session.ArtistSession #aliceblue {
  type : int
  date : NoneType, datetime
  db : Database
  username : str
  navigate_page(url: str) -> None
  get_share_link() -> str
  upload_page(url: str, db: Database) -> None
  delete_page(url: str, db: Database) -> None
  delete_comment(url: str, comment_id: int, db: Database) -> None
  logout() -> None
}
@enduml
